# frozen_string_literal: true

module Woods
  module Watch
    class Installation
      # Small generated fragments; runtime identities never enter committed files.
      module Templates
        START = '# woods:watch:managed:start'
        FINISH = '# woods:watch:managed:end'

        module_function

        # @param child_command [Array<String>] explicit task argv
        # @return [String] application-relative executable source
        def wrapper(child_command)
          <<~RUBY
            #!/usr/bin/env ruby
            # frozen_string_literal: true

            # Generated by Woods; use woods:watch --operation update to change owned setup.
            root = File.expand_path('..', __dir__)
            ENV['BUNDLE_GEMFILE'] ||= File.join(root, 'Gemfile')
            require 'bundler/setup'
            Dir.chdir(root)
            exec Gem.ruby, Gem.bin_path('woods', 'woods-watch'), '--root', root,
                 *ARGV, '--', *#{child_command.inspect}
          RUBY
        end

        # @param mode [String] procfile or puma
        # @return [String] owned startup directive
        def directive(mode)
          mode == 'puma' ? 'plugin :woods if Gem.loaded_specs.key?("woods")' : 'woods: bin/woods-watch'
        end

        # @param mode [String] selected startup mode
        # @param text [String] surrounding file contents
        # @return [String] exact appended owned block including separator
        def section(mode, text)
          newline = text.include?("\r\n") ? "\r\n" : "\n"
          separator = text.empty? || text.end_with?(newline) ? '' : newline
          separator + [START, directive(mode), FINISH, ''].join(newline)
        end
      end
    end
  end
end
