# frozen_string_literal: true

require 'shellwords'
require 'woods/input_rules'

module Woods
  module Hooks
    # Generated Bash predicate: the plugin also runs on hosts with no Ruby/bundle.
    # This is a projection of authoritative rules, never a second path inventory.
    class RuleProjection
      def render
        lines = [
          '# Generated by script/generate-hook-rules; do not edit.',
          'woods_input_action() {',
          '  local path="$1" operation="${2:-update}"'
        ]
        restart_conditions.each { |condition| lines << "  if #{condition}; then printf full; return; fi" }
        lines.concat(declared_root_lines)
        rules.each do |rule|
          lines << "  if #{condition_for(rule)}; then"
          lines << '    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac'
          lines << '    return'
          lines << '  fi'
        end
        lines.push('  printf ignore', '}', '').join("\n")
      end

      private

      # The published index's declared source roots reach the predicate as
      # WOODS_DECLARED_ROOTS (colon separated), exported by the hook from the
      # manifest; a Ruby file under one is incremental input (F15).
      def declared_root_lines
        [
          '  local -a declared_roots=()',
          '  IFS=: read -r -a declared_roots <<< "${WOODS_DECLARED_ROOTS:-}"',
          '  local declared_root',
          '  for declared_root in "${declared_roots[@]+"${declared_roots[@]}"}"; do',
          '    [[ -n "$declared_root" && "$path" == *.rb && "$path" == "${declared_root%/}"/* ]] || continue',
          '    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac',
          '    return',
          '  done'
        ]
      end

      def rules
        PathDispatcher.runtime_rules +
          PathDispatcher.file_rules + PathDispatcher.whole_app_rules
      end

      def restart_conditions
        policy = ReloadPolicy
        conditions = policy::RESTART_PATHS.map { |path| "[[ \"$path\" == #{quote(path)} ]]" }
        conditions += policy::RESTART_DIRECTORIES.map { |dir| "[[ \"$path\" == #{quote("#{dir}/")}* ]]" }
        conditions + policy::RESTART_PATH_PATTERNS.map do |pattern|
          regex = pattern.source.gsub('\\A', '^').gsub('\\z', '$')
          "[[ \"$path\" =~ #{regex} ]]"
        end
      end

      def condition_for(rule)
        alternatives = rule.exact_paths.to_a.map { |path| "[[ \"$path\" == #{quote(path)} ]]" }
        filters = rule.exclude.to_a.map { |part| "[[ \"$path\" != *#{quote(part)}* ]]" }
        filters += if rule.basenames
                     [either(rule.basenames.map { |name| "[[ \"${path##*/}\" == #{quote(name)} ]]" })]
                   else
                     directory_filters(rule)
                   end
        alternatives << "{ #{filters.join(' && ')}; }"
        either(alternatives)
      end

      def directory_filters(rule)
        filters = []
        filters << either(rule.extensions.map { |ext| "[[ \"$path\" == *#{quote(ext)} ]]" }) if rule.extensions
        filters << "[[ \"$path\" == *#{quote(rule.require_segment)}* ]]" if rule.require_segment
        filters << either(rule.dirs.to_a.map { |dir| directory_condition(dir, rule.recursive) })
      end

      def directory_condition(dir, recursive)
        variable = recursive == false ? '${path%/*}' : '$path'
        suffix = recursive == false ? quote(dir) : "#{quote("#{dir}/")}*"
        "[[ \"#{variable}\" == #{suffix} ]]"
      end

      def either(conditions)
        conditions.empty? ? 'false' : "{ #{conditions.join(' || ')}; }"
      end

      def quote(value)
        Shellwords.escape(value)
      end
    end
  end
end
