# Generated by script/generate-hook-rules; do not edit.
woods_input_action() {
  local path="$1" operation="${2:-update}"
  if [[ "$path" == Gemfile ]]; then printf full; return; fi
  if [[ "$path" == Gemfile.lock ]]; then printf full; return; fi
  if [[ "$path" == .ruby-version ]]; then printf full; return; fi
  if [[ "$path" == config/application.rb ]]; then printf full; return; fi
  if [[ "$path" == config/boot.rb ]]; then printf full; return; fi
  if [[ "$path" == config/environment.rb ]]; then printf full; return; fi
  if [[ "$path" == config/database.yml ]]; then printf full; return; fi
  if [[ "$path" == config/credentials.yml.enc ]]; then printf full; return; fi
  if [[ "$path" == config/master.key ]]; then printf full; return; fi
  if [[ "$path" == db/schema.rb ]]; then printf full; return; fi
  if [[ "$path" == db/structure.sql ]]; then printf full; return; fi
  if [[ "$path" == config/initializers/* ]]; then printf full; return; fi
  if [[ "$path" == config/environments/* ]]; then printf full; return; fi
  if [[ "$path" == config/credentials/* ]]; then printf full; return; fi
  if [[ "$path" =~ ^config/settings\.ya?ml$ ]]; then printf full; return; fi
  if [[ "$path" =~ ^config/settings/[^/]+\.ya?ml$ ]]; then printf full; return; fi
  if [[ "$path" =~ ^config/(cable|storage|sidekiq|puma|cache|queue)\.ya?ml$ ]]; then printf full; return; fi
  if [[ "$path" =~ ^\.env(\..+)?$ ]]; then printf full; return; fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/services/* ]] || [[ "$path" == app/interactors/* ]] || [[ "$path" == app/operations/* ]] || [[ "$path" == app/commands/* ]] || [[ "$path" == app/use_cases/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/jobs/* ]] || [[ "$path" == app/workers/* ]] || [[ "$path" == app/sidekiq/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/serializers/* ]] || [[ "$path" == app/blueprinters/* ]] || [[ "$path" == app/decorators/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/managers/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/policies/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/validators/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/policies/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/decorators/* ]] || [[ "$path" == app/presenters/* ]] || [[ "$path" == app/form_objects/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == config/initializers/* ]] || [[ "$path" == config/environments/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && [[ "$path" == */concerns/* ]] && { [[ "$path" == app/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { [[ "$path" != */concerns/* ]] && { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/* ]] || [[ "$path" == lib/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/graphql/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.yml ]]; } && { [[ "$path" == config/locales/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rake ]]; } && { [[ "$path" == lib/tasks/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.html.erb ]] || [[ "$path" == *.erb ]]; } && { [[ "$path" == app/views/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "${path%/*}" == db/migrate ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { [[ "$path" != */concerns/* ]] && { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/models/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { [[ "$path" != */tasks/* ]] && [[ "$path" != */generators/* ]] && { [[ "$path" == *.rb ]]; } && { [[ "$path" == lib/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *_spec.rb ]]; } && { [[ "$path" == spec/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *_test.rb ]]; } && { [[ "$path" == test/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/controllers/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/models/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.erb ]]; } && { [[ "$path" == app/views/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { [[ "$path" == config/routes.rb ]] || { { [[ "$path" == config/routes/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { [[ "$path" == config/routes.rb ]] || [[ "$path" == Gemfile.lock ]] || { { [[ "$path" == config/routes/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { [[ "$path" == config/application.rb ]] || [[ "$path" == Gemfile.lock ]] || { { [[ "$path" == config/initializers/* ]] || [[ "$path" == config/environments/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { [[ "$path" == config/recurring.yml ]] || [[ "$path" == config/sidekiq_cron.yml ]] || [[ "$path" == config/schedule.rb ]] || { false; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/models/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == spec/factories/* ]] || [[ "$path" == test/factories/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.sql ]]; } && { [[ "$path" == db/views/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { { [[ "$path" == *.rb ]]; } && { [[ "$path" == app/* ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { [[ "$path" == Gemfile.lock ]] || { false; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  if { { [[ "$path" != *node_modules/* ]] && [[ "$path" != *vendor/* ]] && [[ "$path" != *tmp/* ]] && [[ "$path" != *bin/* ]] && [[ "$path" != *script/* ]] && { [[ "${path##*/}" == package.yml ]] || [[ "${path##*/}" == packwerk.yml ]]; }; }; }; then
    case "$operation" in delete|move) printf full ;; *) printf incremental ;; esac
    return
  fi
  printf ignore
}
